### ISSUE TITLE
Mangago: `Android internal error`

### ISSUE THREAD

**Issue by xdeiimoss** [keiyoushi/tachiyomi-extensions-source#5441]
### Source information

Mangago 1.4.20

### Source language

English

### Steps to reproduce

1. Download a manga chapter (looks like this happens only in specific ones though)
2. Wait for error to appear

### Expected behavior

The chapter should be downloaded without a problem

### Actual behavior

It gives out this error 
![Screenshot_20241008_150442_Komikku](https://github.com/user-attachments/assets/fdeea1cb-2963-455d-8fbd-8b3d8c2ed28b)

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
I was unable to reproduce the issue for The Pawn's Revenge: Ch.77. Are you still having issues with that chapter? Could it be a transient issue? Do you have any other chapters to test with?

**Comment by xdeiimoss** [comment]
> I was unable to reproduce the issue for The Pawn's Revenge: Ch.77. Are you still having issues with that chapter? Could it be a transient issue? Do you have any other chapters to test with?

This error happens out of nowhere but if I keep trying to download the chapter, the error will eventually stop, but it takes a while
there are some other manga and other chapters that I had this happen before but I can't remember any right now... Will let you know if I do
It happens quite frequently to me

**Comment by xdeiimoss** [comment]
> I was unable to reproduce the issue for The Pawn's Revenge: Ch.77. Are you still having issues with that chapter? Could it be a transient issue? Do you have any other chapters to test with?

It just happened to vol 2 ch 11 of Boku no Papa to Papa no Hanashi. Same error

**Comment by patros36** [comment]
Its happening to me pretty consistently for the last few days for blue lock and Tales of Demons and Gods, both ltest chapters
Im on mihon 0.19.1 and have manhago 1.4.25

**Comment by honggie96** [comment]
It still happens with the new title/chapter

**Comment by AwkwardPeak7** [comment]
```
java.lang.IllegalArgumentException: Invalid input to toASCII: iweb_6.mangapicgallery.com
    at java.net.IDN.toASCII(IDN.java:115)
    at javax.net.ssl.SNIHostName.<init>(SNIHostName.java:99)
    at com.android.org.conscrypt.Platform.getSSLParameters(Platform.java:218)
    at com.android.org.conscrypt.ConscryptEngine.getSSLParameters(ConscryptEngine.java:522)
    at com.android.org.conscrypt.ConscryptEngineSocket.getSSLParameters(ConscryptEngineSocket.java:192)
    at okhttp3.internal.platform.android.Android10SocketAdapter.configureTlsExtensions(Android10SocketAdapter.kt:64)
    ... 30 more
Caused by: The input does not conform to the STD 3 ASCII rules. line:  0. preContext:  . postContext: b_6
    at android.icu.impl.IDNA2003.convertToASCII(IDNA2003.java:218)
    at android.icu.impl.IDNA2003.convertIDNToASCII(IDNA2003.java:276)
    at android.icu.text.IDNA.convertIDNToASCII(IDNA.java:664)
    at com.android.icu.text.ExtendedIDNA.convertIDNToASCII(ExtendedIDNA.java:50)
    at java.net.IDN.toASCII(IDN.java:108)
    ... 35 more
```
happens because of `_` in the domain
