### ISSUE TITLE
komga dont trust certification of Let's Encrypt

### ISSUE THREAD

**Issue by EnderAvaritia** [keiyoushi/tachiyomi-extensions-source#5836]
### Source information

Komga 1.4.58

### Source language

none

### Steps to reproduce

1.add the site using the certification signed by Let's Encrypt
2.enter and error
3.additionally if you enter in webview and quiet ,it can be load normally (it can be viewed in webview)

### Expected behavior

it can be viewed in mihon

### Actual behavior

![Snipaste_2024-11-02_20-13-37](https://github.com/user-attachments/assets/86e62817-8ad7-434b-901f-6146a8e7f272)

### Mihon/Tachiyomi version

0.17.0-6971

### Android version

amdroid 13

### Other details

btw, if i use the certification of DigiCert , it can work correctly (but i cant use the certification of DigiCert  for long time )
the infomation below is the crash report:
```
11-02 20:21:53.204 12298 12408 E komga   : Failed to fetch filtering options
11-02 20:21:53.204 12298 12408 E komga   : java.io.IOException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
11-02 20:21:53.204 12298 12408 E komga   : 	at eu.kanade.tachiyomi.extension.all.komga.Komga$fetchFilterOptions$1.invokeSuspend(Komga.kt:448)
11-02 20:21:53.204 12298 12408 E komga   : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
11-02 20:21:53.204 12298 12408 E komga   : 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:106)
11-02 20:21:53.204 12298 12408 E komga   : 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(Unknown Source:3)
11-02 20:21:53.204 12298 12408 E komga   : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
11-02 20:21:53.204 12298 12408 E komga   : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
11-02 20:21:53.204 12298 12408 E komga   : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:57)
11-02 20:21:53.204 12298 12408 E komga   : Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
11-02 20:21:53.204 12298 12408 E komga   : 	at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:363)
11-02 20:21:53.204 12298 12408 E komga   : 	at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
11-02 20:21:53.204 12298 12408 E komga   : 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
11-02 20:21:53.204 12298 12408 E komga   : 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
11-02 20:21:53.204 12298 12408 E komga   : 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
11-02 20:21:53.204 12298 12408 E komga   : 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
11-02 20:21:53.204 12298 12408 E komga   : 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:858)
11-02 20:21:53.204 12298 12408 E komga   : 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.-$$Nest$mprocessDataFromSocket(Unknown Source:0)
11-02 20:21:53.204 12298 12408 E komga   : 	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:241)
11-02 20:21:53.204 12298 12408 E komga   : 	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220)
11-02 20:21:53.204 12298 12408 E komga   : 	at okhttp3.internal.connection.ConnectPlan.connectTls(Unknown Source:32)
11-02 20:21:53.204 12298 12408 E komga   : 	at okhttp3.internal.connection.ConnectPlan.connectTlsEtc(Unknown Source:159)
11-02 20:21:53.204 12298 12408 E komga   : 	at okhttp3.internal.connection.FastFallbackExchangeFinder.find(Unknown Source:119)
11-02 20:21:53.204 12298 12408 E komga   : 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(Unknown Source:24)
11-02 20:21:53.204 12298 12408 E komga   : 	at okhttp3.internal.connection.ConnectInterceptor.intercept(Unknown Source:9)
11-02 20:21:53.204 12298 12408 E komga   : 	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:142)
11-02 20:21:53.204 12298 12408 E komga   : 	at okhttp3.internal.cache.CacheInterceptor.intercept(Unknown Source:163)
11-02 20:21:53.204 12298 12408 E komga   : 	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:142)
11-02 20:21:53.204 12298 12408 E komga   : 	at okhttp3.internal.http.BridgeInterceptor.intercept(Unknown Source:238)
11-02 20:21:53.204 12298 12408 E komga   : 	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:142)
11-02 20:21:53.204 12298 12408 E komga   : 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(Unknown Source:26)
11-02 20:21:53.204 12298 12408 E komga   : 	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:142)
11-02 20:21:53.204 12298 12408 E komga   : 	at eu.kanade.tachiyomi.network.interceptor.WebViewInterceptor.intercept(SourceFile:2)
11-02 20:21:53.204 12298 12408 E komga   : 	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:142)
11-02 20:21:53.204 12298 12408 E komga   : 	at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(Unknown Source:56)
11-02 20:21:53.204 12298 12408 E komga   : 	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:142)
11-02 20:21:53.204 12298 12408 E komga   : 	at eu.kanade.tachiyomi.network.interceptor.UncaughtExceptionInterceptor.intercept(Unknown Source:9)
11-02 20:21:53.204 12298 12408 E komga   : 	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:142)
11-02 20:21:53.204 12298 12408 E komga   : 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(Unknown Source:99)
11-02 20:21:53.204 12298 12408 E komga   : 	at okhttp3.internal.connection.RealCall$AsyncCall.run(Unknown Source:43)
11-02 20:21:53.204 12298 12408 E komga   : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
11-02 20:21:53.204 12298 12408 E komga   : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
11-02 20:21:53.204 12298 12408 E komga   : 	at java.lang.Thread.run(Thread.java:1012)
11-02 20:21:53.204 12298 12408 E komga   : Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
11-02 20:21:53.204 12298 12408 E komga   : 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:654)
11-02 20:21:53.204 12298 12408 E komga   : 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:503)
11-02 20:21:53.204 12298 12408 E komga   : 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:423)
11-02 20:21:53.204 12298 12408 E komga   : 	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:351)
11-02 20:21:53.204 12298 12408 E komga   : 	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
11-02 20:21:53.204 12298 12408 E komga   : 	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
11-02 20:21:53.204 12298 12408 E komga   : 	at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:163)
11-02 20:21:53.204 12298 12408 E komga   : 	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:255)
11-02 20:21:53.204 12298 12408 E komga   : 	at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1638)
11-02 20:21:53.204 12298 12408 E komga   : 	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
11-02 20:21:53.204 12298 12408 E komga   : 	at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:569)
11-02 20:21:53.204 12298 12408 E komga   : 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
11-02 20:21:53.204 12298 12408 E komga   : 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
11-02 20:21:53.204 12298 12408 E komga   : 	... 30 more
11-02 20:21:53.204 12298 12408 E komga   : Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
11-02 20:21:53.204 12298 12408 E komga   : 	... 43 more
11-02 20:21:58.189 12298 12298 E FileUtils: err write to mi_exception_log
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alexandrejournet** [comment]
Hello, I got the problem too. Any news on this ? (Mihon 0.18 / Komga 1.4.63)

**Comment by gotson** [comment]
Probably because of https://community.letsencrypt.org/t/letsencrypt-certificates-fails-on-android-phones-running-android-7-or-older/205686
